### ISSUE TITLE
Add OpenGL ES 2 renderer

### ISSUE THREAD

**Issue by zuck** [horde3d/Horde3D#10]
Add an OpenGL ES 2-based renderer to support mobile platforms like iOS and Android.

**Work by attila:**
https://github.com/attilaz/horde3d-x/tree/gles2_d3d11

**Discussion on threads:**
http://horde3d.org/forums/viewtopic.php?f=8&t=1886
http://horde3d.org/forums/viewtopic.php?f=8&t=1036

**Comment by lvivtotoro** [comment]
Any updates on this, yet?

**Comment by algts** [comment]
Hello. You can check nearly finished version by attilaz [https://github.com/attilaz/horde3d-x](here). As for official es support in horde3d, I'm making a ES3 renderer, but currently it has major problems with lighting, so it is not yet ready for release and probably won't be ready until the end of the year. It is scheduled for 1.2 release.

**Comment by algts** [comment]
ES3 backend is merged to develop branch.

**Comment by algts** [comment]
Can be closed now

**Comment by algts** [comment]
Can be closed now, OpenGL ES 3 backend is working on Android and IOS.
