### ISSUE TITLE
Buffers are destroyed even if they are still referenced

### ISSUE THREAD

**Issue by horde3d** [horde3d/Horde3D#101]
Currently the terrain extension uses the same vertex buffer two times in it's geometry. Calling destroyGeometry destroys the bound buffers by default and releases the same buffer multiple times because it does not check if a buffer bound previously has been already destroyed. 
Probably the best would be to reference count the _buffer entries and only destroy buffers in destroyGeometry if no one else is using it anymore. Similar to how it is done with the resources. Maybe _buffers should be handled as Resources anyway. This way one vertex buffer may be used in different Geometries if needed.

**Comment by algts** [comment]
Should be fixed in #102

**Comment by horde3d** [comment]
Seems like it is fixed as mentioned with commit #102
