### ISSUE TITLE
`bool TextureResourceEx::importTexGL` does not return anything

### ISSUE THREAD

**Issue by jcmonnin** [horde3d/Horde3D#112]
I've got a compiler warning in following function. The compiler is complaining that the function is not returning anything. Should the function signature be changed to void?

    bool TextureResourceEx::importTexGL(uint32 texGL, int width, int height )
    {
        _loaded = true;
        _width = width;
        _height = height;

        if( _texObject == defTex2DObject )
        {
            m_imported = false;
            RenderDeviceInterface *rdi = Modules::renderer().getRenderDevice();
            _texObject = rdi->createTexture( _texType, _width, _height, _depth == 0 ? 1 : _depth, _texFormat,
                                             false, false, false, _sRGB );
        }
        replaceTexObj( texGL );
        m_imported = true;
    }

**Comment by horde3d** [comment]
Probably yes. I wonder what I have done there...
