### ISSUE TITLE
Please only install into $CMAKE_INSTALL_PREFIX

### ISSUE THREAD

**Issue by yurivict** [horde3d/Horde3D#117]
You currently install into /usr, which isn't the destination on BSDs.

**Comment by algts** [comment]
Umm, for the editor currently only desktop and icon files are installed to usr/share. It is controlled via CMAKE_INSTALL_DATADIR variable that is also shown during configuration (in CMAKE subgroup of CMAKE gui). Editor itself is not installed anywhere and remains in the build directory. Horde itself is installed to the CMAKE_INSTALL_PREFIX.

**Comment by yurivict** [comment]
> Should the editor really be installed somewhere like /usr/bin?
Nothing should be installed into ```/usr/bin```.
It should be installed into ```$CMAKE_INSTALL_PREFIX/bin```, please.

**Comment by algts** [comment]
As I currently understand the editor's structure, it will need plugins and styles folder in the $CMAKE_INSTALL_PREFIX/bin folder. Is it okay to place these folders along the binary in the install directory?

**Comment by algts** [comment]
Could you please try the fix that is in my fork (seems to be working correctly, but you'll have to specify the content folder in the settings before creating a new scene): https://github.com/algts/Horde3D
I'll pull request if everything is okay.
