### ISSUE TITLE
Set position of individual vertex?

### ISSUE THREAD

**Issue by lvivtotoro** [horde3d/Horde3D#121]
Planning on using soft bodies on Bullet, and I couldn't find any public function that would help me on this.

**Comment by lvivtotoro** [comment]
As I understand, the float array consists of all the vertices, so every 3 floats is a new vertex?

**Comment by algts** [comment]
Yes. Please note that geometry resource may contain vertex data for the whole scene. not just one mesh. That's exactly why vertRStart parameter is needed.

**Comment by lvivtotoro** [comment]
Thank you very much, not sure if this is even a good place to ask questions like these, but my forum account hasn't been activated for around 2 months, so this seemed like the next best spot.

**Comment by horde3d** [comment]
Sorry, should be activated now

**Comment by lvivtotoro** [comment]
Thanks!
