### ISSUE TITLE
Add OpenGL 4 renderer

### ISSUE THREAD

**Issue by zuck** [horde3d/Horde3D#14]
Add an OpenGL 4-based renderer to better support modern hardware capabilities (comparing to D3D11).

**Useful links:**

http://www.horde3d.org/forums/viewtopic.php?f=1&t=1904
http://rastergrid.com/blog/2011/10/opengl-vs-directx-the-war-is-far-from-over/

**Comment by algts** [comment]
Done in develop branch. Please close.
