### ISSUE TITLE
[Question] C++11 requirement

### ISSUE THREAD

**Issue by jcmonnin** [horde3d/Horde3D#142]
When submitting patches, I've sometimes committed things that use features from C++11. I think there are also commits from others that rely on C++11 features. I'm wondering if the project should be declared as requiring C++11, or if the code requiring to C++11 should be changed to work on older compilers.

On Windows, C++11 means that it wouldn't compile on anything older than VisualStudio 2015. Any macOS or Linux distribution that is not outdated has C++11 support and also iOS and Android support C++11 since a while.

I would be supporting to declare the project as C++11 project because it gives some useful language features and also because it's hard to test on pre-C++11 compilers. It should not be on the way to make progress to mobile platforms and web like outlined in #134, and I don't think it's worth spending efforts in supporting ancient compilers.

If anyone uses Horde3D with a pre-C++11 compiler, please speak up. If the general opinion is that it should require a C++11 compiler, I can submit a PR to update the README.

**Comment by horde3d** [comment]
I think we can definitely change the project to require C++11 now. So for the git repo feel free to add C++11 as a requirement.

**Comment by algts** [comment]
Yep, I also vote for C++11 requirement. Some things are much easier to do than with 98 standard.
