### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by Xarvie** [horde3d/Horde3D#150]
###Attach:
[models.zip](https://github.com/horde3d/Horde3D/files/3860287/models.zip)
![Horde3D](https://user-images.githubusercontent.com/14047011/69082743-b577bd80-0a7b-11ea-80e4-38d6259805db.png)
![Other](https://user-images.githubusercontent.com/14047011/69082775-c45e7000-0a7b-11ea-9fbf-f1a3a8dbd686.png)
![Blender](https://user-images.githubusercontent.com/14047011/69082780-c6283380-0a7b-11ea-88c3-8c27f6432f61.png)

Is there a problem with the conversion tool, or bad Data? 
doom.dae <skin><bind_shape_matrix>，When I modify "bind_shape_matrix", it works correctly.
Need your help.

**Comment by Xarvie** [comment]
solved

**Comment by horde3d** [comment]
Do you please want to provide some more details what was the problem and how you solved it?

**Comment by Xarvie** [comment]
Issue
In blender, To transform a model and **without** Aplly All Transforms(Ctrl + A), Horde can not display it correctly, like this attach. Maybe there are some bugs related to transform,  hope this 
I Aplly Rotation and export it to Collada , Rendering looks good. 😃 666 😃
This solution is useful to me 💡
or Maybe not Bug.

**Comment by horde3d** [comment]
Thanks for the update. Now I remember the same solution was done by a designer in the university more than ten years ago. So at least this has been the workflow in the past as well. But I have to admit I was never very familiar with Blender.
