### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by algts** [horde3d/Horde3D#161]
Hello. A lot happened since version 1.0 and many things were added. It is probably time to think about new release. There are still some things that I plan to add to Horde before reaching 2.0 release:
- IOS support (in the works)
- Directional lighting support (very early prototype)
- Multithreaded culling, particles and scene graph traversal (not started, may be pushed to 2.1)

There are also things that should be done (or fixed) before the next release:
- compute, tessellation and terrain shaders are not working on Android (OpenGL ES issue)
- fix compute functions to accept H3DMeshPrimType enum (may be renamed) to specify drawing type (triangles, lines, points, patches) instead of using a custom parameter for it as it is done now
- update documentation
- more testing

With this plan, I think we should aim for release in mid or late summer. What do you think?
Thanks.

**Comment by horde3d** [comment]
Thanks a lot for your hard work. I will do my best to create a release package and update the webpage as soon as you think you're done. Unfortunately I can't spent any time for testing or documentation myself. I'm quite busy currently.

**Comment by algts** [comment]
@horde3d Okay, that's fine. I'm thinking about adding some documentation about Horde's internals and extension development. Should I also aim to create api documentation for internal interfaces, like it is done for external interface (Horde3d.h) (it may be done in later versions, not 2.0)?

**Comment by horde3d** [comment]
Actually I have to do some investigation what tool was used for creating the documentation. As far as I remember it was a bit of a mess to create it (I'm more familiar with Doxygen).
But to answer your question, in general having documentation within the source code is a good thing :-)

**Comment by algts** [comment]
Documentation was done with NaturalDocs. It was not very hard to use it, I've written instruction on how to generate documentation when version 1.0 was released, it is in Horde's wiki. 
If you are interested, the instruction is here: http://horde3d.org/wiki/index.php?title=Regenerating_documentation
