### ISSUE TITLE
There is no cmake-gui file

### ISSUE THREAD

**Issue by umustbeloggedintododat** [horde3d/Horde3D#165]
how the hell do I open this?????????????????

**Comment by umustbeloggedintododat** [comment]
im not a smartass I just wanted to open a data.xpk file

**Comment by algts** [comment]
Hello. Can you please clarify what exactly are you trying to open? cmake-gui is a standalone application, it is installed separately from the engine. If you are on windows, installer should install both gui and console versions of the application. On linux, you may have to separately install cmake-gui (on ubuntu and debian it is like that: **sudo apt-get install cmake-qt-gui**). As for mac, the process of installing is similar to windows, you just download the .dmg file from official website, than install cmake from it.

**Comment by umustbeloggedintododat** [comment]
oh
