### ISSUE TITLE
How do I unpack a data.xpk file?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [horde3d/Horde3D#166]
Like I wanna get models, textures, sounds, etc. I heard that Offroad Legends uses this engine and all the data is stored in a file called "data.xpk".

Is there something I can do to do this?

**Comment by algts** [comment]
Offroad Legends uses a custom format to store their resources and it is not understood by Horde3D in any way. Please note that Horde3D is a rendering engine and does not use any custom binary resources, except for geometry files (*.geo) and compressed textures (*.dds, *.ktx). Offroad Legends, on the other hand, uses a custom engine that incorporates Horde3D as renderer part, but also has audio, ai and other subsystems. Therefore, you should search for unpackers on specialized forums or directly ask the developers about their format.

**Comment by umustbeloggedintododat** [comment]
Ah, I see. Offroad Legends doesn't have any model rippers so I can't find any unpackers.
