### ISSUE TITLE
shadow disappears

### ISSUE THREAD

**Issue by creutzerb** [horde3d/Horde3D#178]
Hi,

I have noticed shadows tend to disappear when the camera moves.

For example, in a slightly modified sample, the shadows disappearance coincides with the light passes counter changing.
(bottom right corner, sorry for the bad framing)

https://user-images.githubusercontent.com/10078731/103393885-7395c380-4b25-11eb-8153-ae20b9a63f7b.mp4

It occurs really often : the are 3 lights in the scene, some shadows disappear with 2 light passes, other with 3.

It also happens in the editor.

https://user-images.githubusercontent.com/10078731/103393889-798ba480-4b25-11eb-807e-26a13b0b5483.mp4

Maybe I have missed some indexing option and a shadow map gets overwritten, I'm a beginner with horde3d, no idea what's going on...

Thanks,

(my setup : manjaro linux opengl4, recent horde3d build)

**Comment by algts** [comment]
Hello. How many lights are in the scene in the editor? It seems like a frustum culling issue.

**Comment by algts** [comment]
It seems that there is a bug in shadow generation code. As a quick fix, please change line 1123 in egRenderer.cpp
from
`float minZ = clamp( minf( frustMinZ, bbMinZ ), -1, 1 );`
to
`float minZ = clamp( maxf( frustMinZ, bbMinZ ), -1, 1 );`

Does it help?

**Comment by creutzerb** [comment]
> Hello. How many lights are in the scene in the editor? It seems like a frustum culling issue.

3 lights 


> float minZ = clamp( maxf( frustMinZ, bbMinZ ), -1, 1 );

That's it, the shadows no longer disappear (both in sample and editor). Thank you very much. :+1: 

It's my first time being in this situation : should I do a pull request or something ?

**Comment by algts** [comment]
Sure, I think you can make a pull request (please create a pull request for develop branch). 
Thanks for finding the bug!
