### ISSUE TITLE
unexpected depth

### ISSUE THREAD

**Issue by creutzerb** [horde3d/Horde3D#180]
Hello,

In the process of rendering fog, I tried getting a value for the distance to the camera in the fragment shader.

```
    float camVertexDistance = gl_FragCoord.z / gl_FragCoord.w;
    camVertexDistance /= 25; // far distance
    float fogFactor = exp2( - camVertexDistance * camVertexDistance * LOG2 );
    fogFactor = clamp( fogFactor, 0.0, 1.0 );
    fragColor.rgb = vec3(fogFactor);
```
Unless I am mistaken, I should see the models getting dark smoothly in the distance, but I get the following :
![unexpected_depth](https://user-images.githubusercontent.com/10078731/104089982-9b96cc80-5273-11eb-9fbc-d5d4f80f40d6.png)
( not so smooth transition before the stairs )
I tried the same code elsewhere and got the expected results.
Then again, that could just be me and my incomplete knowledge of the rendering pipeline.

Thanks.

**Comment by algts** [comment]
Hello. What radius and fov are you using for lights? Fov below 180 degrees means that it is a spot light, above means point light. Shadows may work incorrectly for point lights, as far as I know.
Also, if possible, could you please try your code with version 1? Or with develop branch before lighting changes were merged in (seems to be commit https://github.com/horde3d/Horde3D/commit/2236c443d755076758e53c6557d1f1719d13c012)? It will help to determine whether it is a problem with new lighting code or not.
Thanks.

**Comment by creutzerb** [comment]
Hello,
Lights fov : 90°
Lights radius : 20 to 35
I get the same problem using the commit https://github.com/horde3d/Horde3D/commit/2236c443d755076758e53c6557d1f1719d13c012.
Thanks.

**Comment by algts** [comment]
To be clear - the incorrect part is the visible seem near the staircase? And the darker color on the wall and the floor right after the light is also the problem?
I don't have the definite answer - it may be blending issue and you can try to play with BlendMode parameter in the shader context. Does using another pipeline change anything (like using deferred if you are using forward or vice verse)? Also check the global illumination - you can try to remove the link to globalSettings.material.xml in the pipeline.

**Comment by creutzerb** [comment]
Hello,
I don't know how to describe the issue properly, so I tried to get a similar effect on a sample project and succeeded.

step to reproduce :
1) in `shaders/model.shader`, add the following lines at the end of `[[FS_LIGHTING_GL4]]` and `[[FS_AMBIENT_GL4]]` :
```
    float camVertexDistance = gl_FragCoord.z / gl_FragCoord.w;
    camVertexDistance /= 25; //SHADERSETTINGS_FOG_FARCLIPPLANE;
    // calculate fog factor
    const float LOG2 = 1.442695;
    float fogFactor = exp2( - camVertexDistance * camVertexDistance * LOG2 );
    fogFactor = clamp( fogFactor, 0.0, 1.0 );
    // determine final color
    fragColor.rgb = vec3(fogFactor);
```
2) in `models/platform/platform.scene.xml`, add the following lines :
```
    <Group name="lights" tx="0.0" ty="0.0" tz="0.0">
        <Light name="Spot" lightingContext="LIGHTING" shadowContext="SHADOWMAP" fov="90" shadowMapBias="0.005" shadowMapCount="1" shadowSplitLambda="0" material="materials/light.material.xml" radius="20.0" col_R="1.0" col_G="1.0" col_B="1.0" tx="10.84225" ty="10.49018" tz="20.97424" rx="314.99620" ry="138.17609" rz="347.19191"/>
        <Light name="Spot.001" lightingContext="LIGHTING" shadowContext="SHADOWMAP" fov="90" shadowMapBias="0.005" shadowMapCount="1" shadowSplitLambda="0" material="materials/light.material.xml" radius="20.0" col_R="1.0" col_G="1.0" col_B="1.0" tx="-34.91391" ty="23.50556" tz="20.44172" rx="314.99620" ry="182.65522" rz="347.19191"/>
        <Light name="Spot.002" lightingContext="LIGHTING" shadowContext="SHADOWMAP" fov="90" shadowMapBias="0.005" shadowMapCount="1" shadowSplitLambda="0" material="materials/light.material.xml" radius="20.0" col_R="1.0" col_G="1.0" col_B="1.0" tx="58.57356" ty="19.61375" tz="22.31023" rx="314.99620" ry="138.17609" rz="347.19191"/>
    </Group>
```

results in chicago sample :
![chicago_sample](https://user-images.githubusercontent.com/10078731/104160447-74fea000-53f1-11eb-94cc-be666c73f879.png)

In both my project and chicago sample, removing the lights gives the expected result :

![no_light_chicago_sample](https://user-images.githubusercontent.com/10078731/104160764-f35b4200-53f1-11eb-812c-bbea039ef711.png)

Hope this helps, thanks.

**Comment by algts** [comment]
I replicated the case, but I'm still not completely sure what should I be looking at. The rectangles around the lights are here due to the lighting algorithm that culls pixels outside of light area (Renderer::drawLightGeometry function). As you are using the spot, light geometry is cone and some objects seem to be out of the cone, but inside the rectangle of the proccessed pixels of the light. 
You can use debug view (f4 in samples) to see how models are affected by light. 
In the debug view it just looks like the light (I'm talking about the right light on the first image) is incorrectly positioned, because near the camera the light does not affect models, but the light rectangle is overlit. Judging by the parameters of the light (position, rotation, radius) of the light it seems that it correctly handles the models. 

Maybe the distance logic for fog should be reversed? Please take a look at calcPhongSpotLight function in utilityLib/fragLightingGL4.glsl. 

Sorry for the a bit chaotic explanation :)

**Comment by creutzerb** [comment]
I was actually doing non-sense : since the light pass is additive, I needed to fade the color to black in the distance in `[[FS_LIGHTING_GL4]]`.
You helped me further my understanding of the rendering pipeline, thank you !
Hopefully next time I bother you it will actually be a bug ;)
