### ISSUE TITLE
lots and lots of errors on compilation

### ISSUE THREAD

**Issue by Unlimiter** [horde3d/Horde3D#187]
[this](https://p.fr33tux.org/c93d8b) is the gcc error output when compiling this:
```c
// t.c
#include <horde3d/Horde3D.h>
#include <horde3d/Horde3DUtils.h>
int main() {}
```

**Comment by algts** [comment]
Horde is primarily a C++ engine, it was not tested to work in C programs. Although Horde uses C-like interface, it has some incompatibilities with C, like enums in structs.
So currently using Horde with C is no go.
