### ISSUE TITLE
IOS side, not using SDL library methods?

### ISSUE THREAD

**Issue by cwwng** [horde3d/Horde3D#190]
1、The iOS project has been compiled on MacOS, and the Demo runs normally.
2、I wanted to use the generated.a static library for our project, but the SDL library hooks the main function.

Problem：
We only want to use the Horde3D rendering model for one scene in the project. How do we remove the SDL library and it works?

Thank you.

**Comment by algts** [comment]
Hello. Sorry for the late response, only saw it now.
If you wish to use just the engine, then, if you use Xcode, you can see that there is Horde3D target. You can build it (it will be built as a static library) and use it however you want in your project. You can also build engine without samples.
However, samples are currently tied to the samples framework and samples framework only works through SDL on ios for now. So, extracting SDL would be difficult. You could probably write a custom backend for the samples framework but it would be a rather big work.
If you already have your own framework and you need the exact sample for some reason, you can just copy the sample code to your framework to respective parts (initialization, keyboard/mouse handling, update).

**Comment by cwwng** [comment]
> Hello. Sorry for the late response, only saw it now.
> If you wish to use just the engine, then, if you use Xcode, you can see that there is Horde3D target. You can build it (it will be built as a static library) and use it however you want in your project. You can also build engine without samples.
> However, samples are currently tied to the samples framework and samples framework only works through SDL on ios for now. So, extracting SDL would be difficult. You could probably write a custom backend for the samples framework but it would be a rather big work.
> If you already have your own framework and you need the exact sample for some reason, you can just copy the sample code to your framework to respective parts (initialization, keyboard/mouse handling, update).

Understand. Thanks.
