### ISSUE TITLE
ColladaConverter : using `material.name` to make filenames might use reserved filesystem characters

### ISSUE THREAD

**Issue by SuperUserNameMan** [horde3d/Horde3D#193]
Hi,

I was trying to transfer files generated by ColladaConverter from my Linux to a server using Samba/SMB.

That's how I've found that some of the files refuse to upload, because they contain filesystem reserved characters. 

Example  :  ` Test:High-poly:Eyegreen.material.xml ` contains multiple colon `:` characters.

Indeed, I could manually rename all the MakeHuman imported nodes from inside Blender before exporting to `.dae`, but still, I was wondering if it is really a good idea to use `material.name` to generate the filenames of the `.material.xml` ?

I don't have yet enough experience to tell if `material.id` would be safer to use, but when I'm looking into my `.dae` files, the `id=` attributes seems to contain safer strings.

https://github.com/horde3d/Horde3D/blob/c0aa1521a18116459d5dd636b8903fb7873a1faa/Horde3D/Source/ColladaConverter/converter.cpp#L1281

What do you think ? 
Does ColladaConverter deserve a patch ?

**Comment by algts** [comment]
Hello. Sorry for the long response, didn't have access to computer.
Your proposal looks good, and adding new parameter is not a problem. 

Thanks.

**Comment by algts** [comment]
Pull request with changes merged, closing issue. Reopen it if any bugs/changes needed.
