### ISSUE TITLE
Relicensed to a permissive license

### ISSUE THREAD

**Issue by hoacom** [horde3d/Horde3D#212]
Hi, Horde3D is a amazing library and version 3.0 is very promising. But its EPL 1 license limits some usability, so could Horde3D Team consider switching to a more permissive license like MIT, Zlib?

Sorry for my bad English.
Thanks.

**Comment by algts** [comment]
Hello.
Could you please provide some info on how are you limited by the EPL license?

From the wiki:

> According to article 1(b) of the EPL, additions to the original work may be licensed independently, including under a [proprietary license](https://en.wikipedia.org/wiki/Proprietary_software), provided such additions are "separate modules of software" and do not constitute a [derivative work](https://en.wikipedia.org/wiki/Derivative_work).[[11]](https://en.wikipedia.org/wiki/Eclipse_Public_License#cite_note-eplfaq-11)[[8]](https://en.wikipedia.org/wiki/Eclipse_Public_License#cite_note-epl-8) Changes and additions which do constitute a derivative work must be licensed under the same terms and conditions of the EPL, which includes the requirement to make [source code](https://en.wikipedia.org/wiki/Source_code) available.[[8]](https://en.wikipedia.org/wiki/Eclipse_Public_License#cite_note-epl-8) 
Linking to code (for example to a library) licensed under EPL automatically does not mean that your program is a derivative work.

So, basically, you can link with the engine in both static and dynamic forms. Engine also has an extension mechanism that allows you to add new functionality without modifing the base engine. 

As for moving to other license, we should ask original maintainers: @horde3d

**Comment by hoacom** [comment]
I cannot modify the core library and keep it proprietary.  It's really not a big deal, but I think it would be great if it could be done.


Just an opinion.  I always respect the path of the development team and the community.

**Comment by horde3d** [comment]
Since there have been a lot of contributions from different people already, I don''t vote for changing the license. Legaly I guess everything contributer would need to agree, but I'm not a lawyer.
