### ISSUE TITLE
C Language binding

### ISSUE THREAD

**Issue by gwald** [horde3d/Horde3D#214]
I created a C Language header, it works well with TinyCC and mingw gcc.
http://horde3d.org/forums/viewtopic.php?f=1&t=2328&p=10420#p10421

It's very hacky, I just put the enum name before the enum item.
I'm happy to clean it up and submit it with a cmake file as a C binding.

Is it worth doing? if so any advice or feedback before I do?

**Comment by algts** [comment]
I think its ok, you can also make something like:

```
enum H3DRenderDevice
{
    H3D_RENDERDEVICE_OPENGL2 = 2,
    H3D_RENDERDEVICE_OPENGL4 = 4,
    H3D_RENDERDEVICE_OPENGLES3 = 8
};

enum H3DOptions
{
    H3D_OPTIONS_...,
};
```

So, imho, this approach is a tiny bit cleaner...

**Comment by algts** [comment]
Closing as pull request #215 is merged. Reopen if problems arise.
