### ISSUE TITLE
building the scene editor on windows.

### ISSUE THREAD

**Issue by gwald** [horde3d/Horde3D#216]
Hi,
I can build the scene editor in linux, no problem, apt install all the qt5 libs and cmake just work.
But in windows (win7/win10), I can't... which is where most of the 3D art content tools are, so having a windows scene editor is important.

From my testing the old version (v0.8.0 2009 from archive.org) isn't compatible with the current engine.

I followed:
http://horde3d.org/wiki/index.php?title=Horde3D_Scene_Editor

I've tried with VS15, mingw, with  different qt5's, from:
https://download.qt.io/archive/qt/
(I used the .exe downloads)

Does anyone have any tips/guide on compiling it for windows? 
VS version?, QT5 version?

Or can share a windows build?
Ideally, it would be nice if each release also included a windows scene editor.

**Comment by algts** [comment]
Hello. I'll look into it today.
Does the build fail during cmake stage or during building?
Please post an error log, it will help to solve the issue faster.

**Comment by algts** [comment]
For now I can say that Horde3D editor should work with Qt 5 (including 5.15), it is not adapted to Qt 6. I'll post my actions if I successfully compile editor on my machine. Stay tuned :)

**Comment by gwald** [comment]
I tried a few time in win7/win10 VM's.  I couldn't get QT to register in cmake and tried using the binary v.0.8.0 code base with replaced the new src files, which I couldn't build... just a hacky mess!

I will try and replicate your instructions :)


Thanks

**Comment by algts** [comment]
For Qt to register in Cmake, you should click on QT5Dir_NOT_FOUND and select the folder with Qt cmake modules - it is likely <Qt installation directory>/libs/cmake/Qt5.

**Comment by gwald** [comment]
Thanks that helped!
But it couldn't find glu32... it was an old version I downloaded 5.1, apparently that was a common thing, found the patch, but it didnt fix it :/

I've download older stuff just to avoid downloading 20GB of MSVS and QT :/


If you could package your build and share it? that would be great!
I really don't want to deal with QT or MS VS, just for the editor.

I'd rather figure out how to import the editor's scene group file, which I couldn't find an example of :/

**Comment by algts** [comment]
Here is the compiled version: https://www.sendspace.com/file/efoukl
Built from master branch for windows 10 and qt 5.15.2. Uses MSVS 2019 runtime.
You should probably first setup repository in the File->Settings menu (where all the resources are collected). 
When we have a new release I'll prepare the editor binaries for Windows as well.

As for importing scene file, you should load it like other models (like in Knight or Chicago examples).

**Comment by gwald** [comment]
Very much appreciated :)

In my windows 10, it loads and runs perfectly! (without VS runtime).
Thank you heaps!

**Comment by gwald** [comment]
I hope you don't mind, I've reuploaded your build here: https://archive.org/details/algts-horde3d-editor-win-x64-march-2023
If anyone else is interested.

**Comment by gwald** [comment]
I didn't release I had this open, or I would have bumped it.
Close it to avoid confusion.
