### ISSUE TITLE
ColladaConv.exe not processing normal maps

### ISSUE THREAD

**Issue by gwald** [horde3d/Horde3D#219]
https://youtu.be/TjLy36A94jo?t=1183

I used assimp (linked in the video) to convert an obj with a texture and normal image to collada, and it works great.
The converter isn't including the normal shader or image reference.

It's not a big deal, easy to fix in the xml, but could be a pain for new people.

**Comment by algts** [comment]
I don't remember all of the details, but converter does not handle textures and shaders, and only generates scene, geometry, animation and material files. It will output the generated files from collada file to the specified directory. Currently handling textures, shaders and pipelines is up to user.

**Comment by gwald** [comment]
You're right, I remember reading it now! :laughing: 
Source is:

http://horde3d.org/docs/html/_contentpipe.html

**Important Notes**

At the moment there are some restrictions for COLLADA files to be compatible with the converter: All geometry should be stored as triangle data and animations have to be exported as sampled keyframe data.

**Textures**
At the moment, Horde3D does not provide a conditioning pipeline for textures. Textures are directly loaded by the engine from one of the supported image formats.



And..

Materials are often modified by hand or with a scene editor, so it is usually not desired that they get overwritten automatically. For that reason, ColladaConv will not overwrite existing materials, except it is forced to do so with the command line argument -overwriteMats.


Thanks :)
closing
