### ISSUE TITLE
How to delete a patch?

### ISSUE THREAD

**Issue by gwald** [horde3d/Horde3D#227]
Sorry, I had too many tabs open and I thought I was on my fork, please delete.
https://github.com/horde3d/Horde3D/compare/master...gwald:Horde3D:patch-1?expand=1

**Comment by algts** [comment]
I've checked the master and develop branches, SDLFramework.cpp was not updated for a long time. So, your fixes were not pushed to horde's repo. In fact, I thinks you would have a permission error during push.
