### ISSUE TITLE
Change ownership of Render Device & remove global pointer

### ISSUE THREAD

**Issue by zuck** [horde3d/Horde3D#23]
I think we should change a little bit the way the **Render Device**, **Renderer** and **Modules** classes are in relationship. At the moment is a little bit confusing.

The idea is to give ownership of low-level **Renderer** class to **RenderDevice** instead of high-level **Modules** singleton container, this also allows to remove the **gRDI** global pointer.

**Discussion on this thread:**

http://www.horde3d.org/forums/viewtopic.php?f=8&t=1908

**Comment by algts** [comment]
Done in develop branch. Please close.
