### ISSUE TITLE
Horde3D Editor, crashing for me

### ISSUE THREAD

**Issue by gwald** [horde3d/Horde3D#236]
I'm having a problem with the editor crashing.
![image](https://github.com/user-attachments/assets/705fc6b1-314c-4c48-ae60-9b30d16ab1bf)
Both the old (2009) and @algts's new QT editor have the same issue for me, it only happens when I try to 'add attachment'.
Both used to work, not sure what happened... I installed the different versions of MS VS and dot.net SDK and [NTVDMx64](http://www.columbia.edu/~em36/ntvdmx64.html). It's a VM so I tryed removing each one and test, but the crash still persist.

Any ideas or tips to try?

Depends log, add attachment clicked at: 00:01:00.188: Thread 3 exited with code 0 (0x0).

``Error: At least one required implicit or forwarded dependency was not found.
Warning: At rror: At least one required implicit or forwarded dependency was not found.
Warning: At least one delay-load dependency module was not found.
Error: At least one required implicit or forwarded dependency was not found.
Warning: At least one delay-load dependency module was not found.

--------------------------------------------------------------------------------
Starting profile on 03-Sep-24 at 10:00:53 PM

Operating System: Microsoft Windows NT/2000/XP/2003/Vista based Professional (64-bit), version 6.02.9200
Program Executable: c:\windows\system32\CONHOST.EXE
Program Arguments: 0x4
Starting Directory: C:\Windows\
Search Path: C:\w64devkit\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\psx3\sbin;C:\psx3\bin;C:\PSX\PSX\BIN;C:\PSX\GNU\BIN;C:\emulators\NOPSX;C:\emulators\NOPSX\tiny;C:\tcc;C:\extras\assimp;C:\extras\7-Zip;C:\extras\NotePad++;C:\eclipse\plugins\org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.5.v20221102-0933\jre\bin;C:\extras;C:\psx3\sbin\UnxUtils;C:\extras\DOSBox;C:\Program Files\Git\cmd;C:\Users\dev\AppData\Local\Microsoft\WindowsApps;C:\Users\dev\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\dev\AppData\Roaming\mips;C:\Users\dev\AppData\Roaming\mips\mips\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\dev\AppData\Local\Microsoft\WindowsApps;C:\extras\CMake\bin;C:\Users\dev\AppData\Local\Programs\Microsoft VS Code\bin

Options Selected:
     Log DllMain calls for process attach and process detach messages.
     Log DllMain calls for all other messages, including thread attach and thread detach.
     Hook the process to gather more detailed dependency information.
     Log LoadLibrary function calls.
     Log GetProcAddress function calls.
     Log thread information.
     Use simple thread numbers instead of actual thread IDs.
     Log first chance exceptions.
     Log debug output messages.
     Log a time stamp with each line of log.
     Automatically open and profile child processes.
--------------------------------------------------------------------------------

00:00:00.000: Started "CONHOST.EXE" (process 0x850) at address 0x00007FF7A3600000 by thread 1.  Successfully hooked module.
00:00:00.000: Loaded "NTDLL.DLL" at address 0x00007FFD1F860000 by thread 1.  Successfully hooked module.
00:00:00.016: Loaded "KERNEL32.DLL" at address 0x00007FFD1F480000 by thread 1.  Successfully hooked module.
00:00:00.016: Loaded "KERNELBASE.DLL" at address 0x00007FFD1C190000 by thread 1.  Successfully hooked module.
00:00:00.016: DllMain(0x00007FFD1C190000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" called by thread 1.
00:00:00.016: DllMain(0x00007FFD1C190000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" returned 1 (0x1) by thread 1.
00:00:00.016: DllMain(0x00007FFD1F480000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" called by thread 1.
00:00:00.016: DllMain(0x00007FFD1F480000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL32.DLL" returned 1 (0x1) by thread 1.
00:00:00.016: Injected "DEPENDS.DLL" at address 0x00000000731A0000 by thread 1.
00:00:00.016: DllMain(0x00000000731A0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DEPENDS.DLL" called by thread 1.
00:00:00.110: DllMain(0x00000000731A0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DEPENDS.DLL" returned 1 (0x1) by thread 1.
00:00:00.172: Loaded "MSVCRT.DLL" at address 0x00007FFD1ECA0000 by thread 1.  Successfully hooked module.
00:00:00.172: Entrypoint reached. All implicit modules have been loaded.
00:00:00.172: DllMain(0x00007FFD1ECA0000, DLL_PROCESS_ATTACH, 0x000000085794F9E0) in "MSVCRT.DLL" called by thread 1.
00:00:00.172: DllMain(0x00007FFD1ECA0000, DLL_PROCESS_ATTACH, 0x000000085794F9E0) in "MSVCRT.DLL" returned 1 (0x1) by thread 1.
00:00:00.172: Loaded "CONHOSTV1.DLL" at address 0x00007FFD0FD40000 by thread 1.  Successfully hooked module.
00:00:03.297: Loaded "WIN32U.DLL" at address 0x00007FFD1BDF0000 by thread 1.  Successfully hooked module.
00:00:03.313: Loaded "USER32.DLL" at address 0x00007FFD1E820000 by thread 1.  Successfully hooked module.
00:00:03.313: Loaded "GDI32.DLL" at address 0x00007FFD1F040000 by thread 1.  Successfully hooked module.
00:00:03.313: Loaded "GDI32FULL.DLL" at address 0x00007FFD1CC60000 by thread 1.  Successfully hooked module.
00:00:03.344: Thread 2 started in "NTDLL.DLL" at address 0x00007FFD1F892800.
00:00:03.344: Thread 3 started in "NTDLL.DLL" at address 0x00007FFD1F892800.
00:00:03.344: Loaded "IMM32.DLL" at address 0x00007FFD1CDF0000 by thread 1.  Successfully hooked module.
00:00:03.344: Thread 4 started in "NTDLL.DLL" at address 0x00007FFD1F892800.
00:00:03.344: Loaded "OLEAUT32.DLL" at address 0x00007FFD1F350000 by thread 1.  Successfully hooked module.
00:00:03.344: Loaded "UCRTBASE.DLL" at address 0x00007FFD1CB60000 by thread 1.  Successfully hooked module.
00:00:03.375: Loaded "COMBASE.DLL" at address 0x00007FFD1F080000 by thread 1.  Successfully hooked module.
00:00:03.375: Loaded "RPCRT4.DLL" at address 0x00007FFD1F530000 by thread 1.  Successfully hooked module.
00:00:03.375: Loaded "BCRYPTPRIMITIVES.DLL" at address 0x00007FFD1CAF0000 by thread 1.  Successfully hooked module.
00:00:03.375: DllMain(0x00007FFD1CC60000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "GDI32FULL.DLL" called by thread 1.
00:00:03.375: DllMain(0x00007FFD1CC60000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "GDI32FULL.DLL" returned 1 (0x1) by thread 1.
00:00:03.375: DllMain(0x00007FFD1F040000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "GDI32.DLL" called by thread 1.
00:00:03.375: DllMain(0x00007FFD1F040000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "GDI32.DLL" returned 1 (0x1) by thread 1.
00:00:03.391: DllMain(0x00007FFD1E820000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "USER32.DLL" called by thread 1.
00:00:03.391: DllMain(0x00007FFD1E820000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "USER32.DLL" returned 1 (0x1) by thread 1.
00:00:03.391: DllMain(0x00007FFD1CDF0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "IMM32.DLL" called by thread 1.
00:00:03.391: DllMain(0x00007FFD1CDF0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "IMM32.DLL" returned 1 (0x1) by thread 1.
00:00:03.391: DllMain(0x00007FFD1CB60000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "UCRTBASE.DLL" called by thread 1.
00:00:03.391: DllMain(0x00007FFD1CB60000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "UCRTBASE.DLL" returned 1 (0x1) by thread 1.
00:00:03.391: DllMain(0x00007FFD1F530000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "RPCRT4.DLL" called by thread 1.
00:00:03.391: DllMain(0x00007FFD1F530000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "RPCRT4.DLL" returned 525953281 (0x1F596901) by thread 1.
00:00:03.407: DllMain(0x00007FFD1CAF0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "BCRYPTPRIMITIVES.DLL" called by thread 1.
00:00:03.407: DllMain(0x00007FFD1CAF0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "BCRYPTPRIMITIVES.DLL" returned 1 (0x1) by thread 1.
00:00:03.407: DllMain(0x00007FFD1F080000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COMBASE.DLL" called by thread 1.
00:00:03.407: DllMain(0x00007FFD1F080000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COMBASE.DLL" returned 1 (0x1) by thread 1.
00:00:03.407: DllMain(0x00007FFD1F350000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "OLEAUT32.DLL" called by thread 1.
00:00:03.422: DllMain(0x00007FFD1F350000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "OLEAUT32.DLL" returned 1 (0x1) by thread 1.
00:00:03.422: DllMain(0x00007FFD0FD40000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "CONHOSTV1.DLL" called by thread 1.
00:00:03.422: DllMain(0x00007FFD0FD40000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "CONHOSTV1.DLL" returned 1 (0x1) by thread 1.
00:00:03.422: Thread 5 started in "CONHOSTV1.DLL" at address 0x00007FFD0FD45BE0.
00:00:03.422: DllMain(0x00007FFD1C190000, DLL_THREAD_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" called by thread 5.
00:00:03.422: DllMain(0x00007FFD1C190000, DLL_THREAD_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" returned 1 (0x1) by thread 5.
00:00:03.422: DllMain(0x00007FFD1ECA0000, DLL_THREAD_ATTACH, 0x0000000000000000) in "MSVCRT.DLL" called by thread 5.
00:00:03.422: DllMain(0x00007FFD1ECA0000, DLL_THREAD_ATTACH, 0x0000000000000000) in "MSVCRT.DLL" returned 1 (0x1) by thread 5.
00:00:03.422: DllMain(0x00007FFD1CDF0000, DLL_THREAD_ATTACH, 0x0000000000000000) in "IMM32.DLL" called by thread 5.
00:00:03.422: DllMain(0x00007FFD1CDF0000, DLL_THREAD_ATTACH, 0x0000000000000000) in "IMM32.DLL" returned 1 (0x1) by thread 5.
00:00:03.422: DllMain(0x00007FFD1F350000, DLL_THREAD_ATTACH, 0x0000000000000000) in "OLEAUT32.DLL" called by thread 5.
00:00:03.422: DllMain(0x00007FFD1F350000, DLL_THREAD_ATTACH, 0x0000000000000000) in "OLEAUT32.DLL" returned 1 (0x1) by thread 5.
00:00:03.422: DllMain(0x00007FFD1CB60000, DLL_THREAD_ATTACH, 0x0000000000000000) in "UCRTBASE.DLL" called by thread 5.
00:00:03.422: DllMain(0x00007FFD1CB60000, DLL_THREAD_ATTACH, 0x0000000000000000) in "UCRTBASE.DLL" returned 1 (0x1) by thread 5.
00:00:03.422: DllMain(0x00007FFD1F080000, DLL_THREAD_ATTACH, 0x0000000000000000) in "COMBASE.DLL" called by thread 5.
00:00:03.438: DllMain(0x00007FFD1F080000, DLL_THREAD_ATTACH, 0x0000000000000000) in "COMBASE.DLL" returned 1 (0x1) by thread 5.
00:00:03.438: DllMain(0x00007FFD1F530000, DLL_THREAD_ATTACH, 0x0000000000000000) in "RPCRT4.DLL" called by thread 5.
00:00:03.438: DllMain(0x00007FFD1F530000, DLL_THREAD_ATTACH, 0x0000000000000000) in "RPCRT4.DLL" returned 525941249 (0x1F593A01) by thread 5.
00:00:03.438: DllMain(0x00007FFD1F350000, DLL_THREAD_DETACH, 0x0000000000000000) in "OLEAUT32.DLL" called by thread 1.
00:00:03.438: DllMain(0x00007FFD1F350000, DLL_THREAD_DETACH, 0x0000000000000000) in "OLEAUT32.DLL" returned 1 (0x1) by thread 1.
00:00:03.438: DllMain(0x00007FFD1F080000, DLL_THREAD_DETACH, 0x0000000000000000) in "COMBASE.DLL" called by thread 1.
00:00:03.438: DllMain(0x00007FFD1F080000, DLL_THREAD_DETACH, 0x0000000000000000) in "COMBASE.DLL" returned 1 (0x1) by thread 1.
00:00:03.438: DllMain(0x00007FFD1F530000, DLL_THREAD_DETACH, 0x0000000000000000) in "RPCRT4.DLL" called by thread 1.
00:00:03.438: DllMain(0x00007FFD1F530000, DLL_THREAD_DETACH, 0x0000000000000000) in "RPCRT4.DLL" returned 1470611457 (0x57A7C001) by thread 1.
00:00:03.438: DllMain(0x00007FFD1CB60000, DLL_THREAD_DETACH, 0x0000000000000000) in "UCRTBASE.DLL" called by thread 1.
00:00:03.438: DllMain(0x00007FFD1CB60000, DLL_THREAD_DETACH, 0x0000000000000000) in "UCRTBASE.DLL" returned 1 (0x1) by thread 1.
00:00:03.438: DllMain(0x00007FFD1CDF0000, DLL_THREAD_DETACH, 0x0000000000000000) in "IMM32.DLL" called by thread 1.
00:00:03.438: DllMain(0x00007FFD1CDF0000, DLL_THREAD_DETACH, 0x0000000000000000) in "IMM32.DLL" returned 1 (0x1) by thread 1.
00:00:03.438: DllMain(0x00007FFD1ECA0000, DLL_THREAD_DETACH, 0x0000000000000000) in "MSVCRT.DLL" called by thread 1.
00:00:03.454: DllMain(0x00007FFD1ECA0000, DLL_THREAD_DETACH, 0x0000000000000000) in "MSVCRT.DLL" returned 1 (0x1) by thread 1.
00:00:03.454: DllMain(0x00007FFD1C190000, DLL_THREAD_DETACH, 0x0000000000000000) in "KERNELBASE.DLL" called by thread 1.
00:00:03.454: DllMain(0x00007FFD1C190000, DLL_THREAD_DETACH, 0x0000000000000000) in "KERNELBASE.DLL" returned 1470611457 (0x57A7C001) by thread 1.
00:00:03.454: Thread 1 exited with code 0 (0x0).
00:00:03.454: Loaded "UXTHEME.DLL" at address 0x00007FFD1A6A0000 by thread 5.  Successfully hooked module.
00:00:03.454: DllMain(0x00007FFD1A6A0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "UXTHEME.DLL" called by thread 5.
00:00:03.454: DllMain(0x00007FFD1A6A0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "UXTHEME.DLL" returned 1 (0x1) by thread 5.
00:00:03.454: Thread 6 started in "CONHOSTV1.DLL" at address 0x00007FFD0FD49EB0.
00:00:03.454: DllMain(0x00007FFD1C190000, DLL_THREAD_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" called by thread 6.
00:00:03.454: DllMain(0x00007FFD1C190000, DLL_THREAD_ATTACH, 0x0000000000000000) in "KERNELBASE.DLL" returned 1 (0x1) by thread 6.
00:00:03.454: DllMain(0x00007FFD1ECA0000, DLL_THREAD_ATTACH, 0x0000000000000000) in "MSVCRT.DLL" called by thread 6.
00:00:03.454: DllMain(0x00007FFD1ECA0000, DLL_THREAD_ATTACH, 0x0000000000000000) in "MSVCRT.DLL" returned 1 (0x1) by thread 6.
00:00:03.454: DllMain(0x00007FFD1CDF0000, DLL_THREAD_ATTACH, 0x0000000000000000) in "IMM32.DLL" called by thread 6.
00:00:03.454: DllMain(0x00007FFD1CDF0000, DLL_THREAD_ATTACH, 0x0000000000000000) in "IMM32.DLL" returned 1 (0x1) by thread 6.
00:00:03.469: DllMain(0x00007FFD1F350000, DLL_THREAD_ATTACH, 0x0000000000000000) in "OLEAUT32.DLL" called by thread 6.
00:00:03.469: DllMain(0x00007FFD1F350000, DLL_THREAD_ATTACH, 0x0000000000000000) in "OLEAUT32.DLL" returned 1 (0x1) by thread 6.
00:00:03.469: DllMain(0x00007FFD1CB60000, DLL_THREAD_ATTACH, 0x0000000000000000) in "UCRTBASE.DLL" called by thread 6.
00:00:03.469: DllMain(0x00007FFD1CB60000, DLL_THREAD_ATTACH, 0x0000000000000000) in "UCRTBASE.DLL" returned 1 (0x1) by thread 6.
00:00:03.469: DllMain(0x00007FFD1F080000, DLL_THREAD_ATTACH, 0x0000000000000000) in "COMBASE.DLL" called by thread 6.
00:00:03.469: DllMain(0x00007FFD1F080000, DLL_THREAD_ATTACH, 0x0000000000000000) in "COMBASE.DLL" returned 1 (0x1) by thread 6.
00:00:03.469: DllMain(0x00007FFD1F530000, DLL_THREAD_ATTACH, 0x0000000000000000) in "RPCRT4.DLL" called by thread 6.
00:00:03.469: DllMain(0x00007FFD1F530000, DLL_THREAD_ATTACH, 0x0000000000000000) in "RPCRT4.DLL" returned 525941249 (0x1F593A01) by thread 6.
00:00:03.469: Error writing a breakpoint at the entrypoint return of "".  Entrypoint cannot be hooked. Invalid access to memory location (998).
00:00:03.469: Loaded "" at address 0x0000012D4B5D0000 by thread 6.  Successfully hooked module.
00:00:03.485: Unloaded "" at address 0x0000012D4B5D0000 by thread 6.
00:00:03.485: Loaded "MSCTF.DLL" at address 0x00007FFD1ED40000 by thread 6.  Successfully hooked module.
00:00:03.485: Loaded "SECHOST.DLL" at address 0x00007FFD1EEA0000 by thread 6.  Successfully hooked module.
00:00:03.485: DllMain(0x00007FFD1EEA0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "SECHOST.DLL" called by thread 6.
00:00:03.485: DllMain(0x00007FFD1EEA0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "SECHOST.DLL" returned 518987777 (0x1EEF2001) by thread 6.
00:00:03.485: DllMain(0x00007FFD1ED40000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "MSCTF.DLL" called by thread 6.
00:00:03.485: DllMain(0x00007FFD1ED40000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "MSCTF.DLL" returned 1 (0x1) by thread 6.
00:00:03.485: Loaded "DWMAPI.DLL" at address 0x00007FFD19AC0000 by thread 6.  Successfully hooked module.
00:00:03.500: DllMain(0x00007FFD19AC0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DWMAPI.DLL" called by thread 6.
00:00:03.500: DllMain(0x00007FFD19AC0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "DWMAPI.DLL" returned 1 (0x1) by thread 6.
00:00:03.516: Loaded "COMCTL32.DLL" at address 0x00007FFD107C0000 by thread 6.  Successfully hooked module.
00:00:03.516: DllMain(0x00007FFD107C0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COMCTL32.DLL" called by thread 6.
00:00:03.516: DllMain(0x00007FFD107C0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "COMCTL32.DLL" returned 1 (0x1) by thread 6.
00:00:03.516: Loaded "KERNEL.APPCORE.DLL" at address 0x00007FFD1BDD0000 by thread 6.  Successfully hooked module.
00:00:03.547: DllMain(0x00007FFD1BDD0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL.APPCORE.DLL" called by thread 6.
00:00:03.547: DllMain(0x00007FFD1BDD0000, DLL_PROCESS_ATTACH, 0x0000000000000000) in "KERNEL.APPCORE.DLL" returned 3419791105 (0xCBD5DF01) by thread 6.
00:01:00.188: Thread 3 exited with code 0 (0x0).
00:01:00.188: Thread 4 exited with code 0 (0x0).
00:01:00.188: Thread 2 exited with code 0 (0x0).
00:01:08.688: Thread 6 exited with code 0 (0x0).
00:01:08.688: DllMain(0x00007FFD1BDD0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "KERNEL.APPCORE.DLL" called by thread 5.
00:01:08.688: DllMain(0x00007FFD1BDD0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "KERNEL.APPCORE.DLL" returned 467481857 (0x1BDD3501) by thread 5.
00:01:08.688: DllMain(0x00007FFD107C0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "COMCTL32.DLL" called by thread 5.
00:01:08.688: DllMain(0x00007FFD107C0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "COMCTL32.DLL" returned 1 (0x1) by thread 5.
00:01:08.688: DllMain(0x00007FFD19AC0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "DWMAPI.DLL" called by thread 5.
00:01:08.688: DllMain(0x00007FFD19AC0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "DWMAPI.DLL" returned 1 (0x1) by thread 5.
00:01:08.688: DllMain(0x00007FFD1ED40000, DLL_PROCESS_DETACH, 0x0000000000000001) in "MSCTF.DLL" called by thread 5.
00:01:08.688: DllMain(0x00007FFD1ED40000, DLL_PROCESS_DETACH, 0x0000000000000001) in "MSCTF.DLL" returned 1 (0x1) by thread 5.
00:01:08.688: DllMain(0x00007FFD1EEA0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "SECHOST.DLL" called by thread 5.
00:01:08.688: DllMain(0x00007FFD1EEA0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "SECHOST.DLL" returned 1 (0x1) by thread 5.
00:01:08.688: DllMain(0x00007FFD1A6A0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "UXTHEME.DLL" called by thread 5.
00:01:08.688: DllMain(0x00007FFD1A6A0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "UXTHEME.DLL" returned 1 (0x1) by thread 5.
00:01:08.688: DllMain(0x00007FFD0FD40000, DLL_PROCESS_DETACH, 0x0000000000000001) in "CONHOSTV1.DLL" called by thread 5.
00:01:08.688: DllMain(0x00007FFD0FD40000, DLL_PROCESS_DETACH, 0x0000000000000001) in "CONHOSTV1.DLL" returned 1 (0x1) by thread 5.
00:01:08.688: DllMain(0x00007FFD1F350000, DLL_PROCESS_DETACH, 0x0000000000000001) in "OLEAUT32.DLL" called by thread 5.
00:01:08.688: DllMain(0x00007FFD1F350000, DLL_PROCESS_DETACH, 0x0000000000000001) in "OLEAUT32.DLL" returned 1 (0x1) by thread 5.
00:01:08.688: DllMain(0x00007FFD1F080000, DLL_PROCESS_DETACH, 0x0000000000000001) in "COMBASE.DLL" called by thread 5.
00:01:08.688: DllMain(0x00007FFD1F080000, DLL_PROCESS_DETACH, 0x0000000000000001) in "COMBASE.DLL" returned 1 (0x1) by thread 5.
00:01:08.704: DllMain(0x00007FFD1CAF0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "BCRYPTPRIMITIVES.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1CAF0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "BCRYPTPRIMITIVES.DLL" returned 1 (0x1) by thread 5.
00:01:08.704: DllMain(0x00007FFD1F530000, DLL_PROCESS_DETACH, 0x0000000000000001) in "RPCRT4.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1F530000, DLL_PROCESS_DETACH, 0x0000000000000001) in "RPCRT4.DLL" returned 525941249 (0x1F593A01) by thread 5.
00:01:08.704: DllMain(0x00007FFD1CB60000, DLL_PROCESS_DETACH, 0x0000000000000001) in "UCRTBASE.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1CB60000, DLL_PROCESS_DETACH, 0x0000000000000001) in "UCRTBASE.DLL" returned 1 (0x1) by thread 5.
00:01:08.704: DllMain(0x00007FFD1CDF0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "IMM32.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1CDF0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "IMM32.DLL" returned 1 (0x1) by thread 5.
00:01:08.704: DllMain(0x00007FFD1E820000, DLL_PROCESS_DETACH, 0x0000000000000001) in "USER32.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1E820000, DLL_PROCESS_DETACH, 0x0000000000000001) in "USER32.DLL" returned 1 (0x1) by thread 5.
00:01:08.704: DllMain(0x00007FFD1F040000, DLL_PROCESS_DETACH, 0x0000000000000001) in "GDI32.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1F040000, DLL_PROCESS_DETACH, 0x0000000000000001) in "GDI32.DLL" returned 1 (0x1) by thread 5.
00:01:08.704: DllMain(0x00007FFD1CC60000, DLL_PROCESS_DETACH, 0x0000000000000001) in "GDI32FULL.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1CC60000, DLL_PROCESS_DETACH, 0x0000000000000001) in "GDI32FULL.DLL" returned 1 (0x1) by thread 5.
00:01:08.704: DllMain(0x00007FFD1ECA0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "MSVCRT.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1ECA0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "MSVCRT.DLL" returned 1 (0x1) by thread 5.
00:01:08.704: DllMain(0x00000000731A0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "DEPENDS.DLL" called by thread 5.
00:01:08.704: DllMain(0x00000000731A0000, DLL_PROCESS_DETACH, 0x0000000000000001) in "DEPENDS.DLL" returned 1 (0x1) by thread 5.
00:01:08.704: DllMain(0x00007FFD1F480000, DLL_PROCESS_DETACH, 0x0000000000000001) in "KERNEL32.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1F480000, DLL_PROCESS_DETACH, 0x0000000000000001) in "KERNEL32.DLL" returned 473431553 (0x1C37FE01) by thread 5.
00:01:08.704: DllMain(0x00007FFD1C190000, DLL_PROCESS_DETACH, 0x0000000000000001) in "KERNELBASE.DLL" called by thread 5.
00:01:08.704: DllMain(0x00007FFD1C190000, DLL_PROCESS_DETACH, 0x0000000000000001) in "KERNELBASE.DLL" returned 473437953 (0x1C381701) by thread 5.
00:01:08.704: Exited "CONHOST.EXE" (process 0x850) with code 0 (0x0) by thread 5.

``

**Comment by algts** [comment]
Hello. Can you provide a simple example where this behavior can be reproduced? It seems that there is a null pointer reference somewhere, judging by the error.

**Comment by algts** [comment]
I've reproduced the crash, the problem was the null pointer for scenenode when calling "Add attachment". I've added a check that prevents the crash. Are you sure you want to use attachments? They were developed for GameEngine that was based on Horde3D. We are not building editor with GameEngine support, so attachments should not work/add anything valuable.
Pushed changes to develop branch. Will make a link to binaries later.

**Comment by algts** [comment]
Here are the binaries for Windows: https://www.sendspace.com/file/1e80p6
Built with MSVC 2019 (should work on Win 10 and later).

**Comment by gwald** [comment]
OOOooohh boy!
It's been a few months I've used the editor and completely forgot what attachment means. :/
Sorry! wow! - I wanted reference... to add models to the scene.

Thanks for the reply... I was going crazy!!
And thanks for the updated editor.
