### ISSUE TITLE
Move Overlays logic to an extension

### ISSUE THREAD

**Issue by zuck** [horde3d/Horde3D#29]
I propose to move all the Overlays logic to a separated extension.

**Why?**

Well, basically because:
1. In real use cases, I think, a stand-alone GUI solution is used instead of basic Overlays.
2. Overlays are just a restricted use case of, more general, geometry primitives drawing (see: #24)
3. Split the core from extension concepts is usually a winning idea.

**Discussion on this thread:**

http://www.horde3d.org/forums/viewtopic.php?f=8&t=2162

**Comment by algts** [comment]
Done in develop branch.

**Comment by zuck** [comment]
Fix with 4d4263da6f0fdd9b6f51759fabd7d88739016e31.
