### ISSUE TITLE
Problems loading resources

### ISSUE THREAD

**Issue by spongebob** [horde3d/Horde3D#73]
Hi! Not sure if this is a bug or if I'm screwing something up, I just recently started tinkering with Horde3D master repos.

While trying to adapt the SDL example to SDL2 I've come across a weird problem, I try to load the pipelines as resources:

```C
    H3DRes test = h3dAddResource(H3DResTypes::Pipeline, "pipelines/forward.pipeline.xml", 0);
    if (!h3dutLoadResourcesFromDisk("<full and relative path to Horde3D/Horde3D/Binaries/Content tried>")) {
        if (!h3dutDumpMessages()) {
            fprintf(stderr, "ERROR: unable to log?\n");
        }
        fprintf(stderr, "ERROR: unable to load resources\n");
    }
```
`h3dutLoadResourcesFromDisk` always returns false, I've tried relative paths, and "." (copying all the content to my local path). 

I tried dumping messages to a log to maybe find out why, but there is no log file available and no output to stdout/stderr. Subsequent call to `h3dGetError` returns false and tried setting MaxLogLevel to both 0 and 1000, neither has given any output afaik.

First, I'm wondering what I'm doing wrong since I'm unable to load any resources (the samples work fine) and secondly I'm wondering how to get information about WHAT the actual error is. Error parsing XML? Error finding the file? So far I've seen no output from Horde3D at all regardless of MaxLogLevel, is there no way to find out what error actually occured when calling a function?
 
Thanks for the help!

**Comment by zuck** [comment]
Are you using the code from **master** or **develop** branch?

**Comment by zuck** [comment]
Could you please test it with recent *develop* branch (>= bb160df3ee5dae3dfa7a5b70ea724d56f74f9764), please?

**Comment by spongebob** [comment]
Hi guys! Sorry for the long absence. I have abandoned my tests with Horde3D, I could try and dig those up and get back to you on this topic. Hopefully, the second time around I'll get it right and there's no problem. :) Give me some time.

**Comment by spongebob** [comment]
Ok, so the test I wrote can now (seemingly, I haven't gotten it to render anything) load the resources.

If I set the wrong filenames h3dutLoadResourcesFromDisk will return false and the error will appear in the HTML log.

Close it!
