### ISSUE TITLE
warning: ‘XKeycodeToKeysym’ is deprecated

### ISSUE THREAD

**Issue by spongebob** [horde3d/Horde3D#80]
Hi!

Just cloned the master head when revisiting an older test case, getting some deprecation warnings.

This is just a warning, but considering everything else in Horde3D is pedantic perfect, you'd want to fix this too perhaps. It's an easy fix:
http://stackoverflow.com/questions/9838385/replace-of-xkeycodetokeysym

I could even provide a patch, although it looks like a case of copy paste from the already found sollution.

**Comment by zuck** [comment]
Could you verify if the issue is present also on *develop* branch, please?

**Comment by zuck** [comment]
Fixed in **develop** branch.
