### ISSUE TITLE
terrain example show black screen no error message

### ISSUE THREAD

**Issue by chriscamacho** [horde3d/Horde3D#85]
Tested with Void Linux on (nvidia) gt640 gpu and also on an intel HD5500 gpu, tried adding content dir for in place running without effect (but still no error)

**Comment by chriscamacho** [comment]
_contentDir = appDir + "../../../Horde3D/Binaries/Content" + "|" + appDir + "/Content" + "|" + appDir + "../Content" + "|" + appDir + "../../../Extensions/Terrain/Sample/Content";

allows it to run in place, there should be a copy to the binaries folder in the Makefile?

could do with some error messages!

**Comment by algts** [comment]
Are you using an engine version from the master branch or from the develop branch? Sample in the master branch does not check if the files were loaded successfully. You can check if anything went wrong in the Horde3D_Log.html. Sample in the develop branch will return an error if resources are not loaded.

**Comment by zuck** [comment]
No feedback, I close it. Please feel free to open again if someone else could reproduce it.
