### ISSUE TITLE
Terrain shows geometry artifacts

### ISSUE THREAD

**Issue by chriscamacho** [horde3d/Horde3D#86]
Occasionally you can see extra triangles in the terrain.

These are most noticable if you go "under" the terrain and can see that every other triangle is exactly vertical

from the top of the terrain you see all the triangles and some extra ones you shouldn't

**Comment by algts** [comment]
Please provide some screenshots. There are indeed some triangles beneath the terrain and they are deliberately created in order to hide cracks between sections with different level of detail. I was unable to find extra triangles from the top. Other than that I don't see any problems (nvidia 960 card). It may also be a driver issue.

**Comment by chriscamacho** [comment]
http://bedroomcoders.co.uk/tmp/terrain3.png
http://bedroomcoders.co.uk/tmp/terrain2.png
http://bedroomcoders.co.uk/tmp/terrain1.png

Intel HD5500 GPU handles terrains using wine (GTA 5) and natively (Mad Max) at good frame rates, not seen issues like this with any other demo's or games or code I've written myself

**Comment by algts** [comment]
Seems like a driver issue. 
Screens from my machine (win 10, nvidia 960 gtx, 372.90 driver version; and intel hd 530, drivers from mid 2016):
https://i.imgsafe.org/d5cf2da5be.png
https://i.imgsafe.org/d5cf4e8cf9.png

I tried with the terrain sample from my fork, but it is pretty much the same as the version in the develop branch (only calls to render device are a bit different, logic is the same).

**Comment by zuck** [comment]
While probably it is a driver issue, I think we need to investigate more to be sure and see if we can mitigate the problem.

My configuration:

```
OS:             Ubuntu 16.04
Graphics:       Intel® HD Graphics 4000 (rev 09)
filename:       /lib/modules/4.10.0-33-generic/kernel/drivers/gpu/drm/i915/i915.ko
description:    Intel Graphics
author:         Intel Corporation
author:         Tungsten Graphics, Inc.
firmware:       i915/bxt_dmc_ver1_07.bin
firmware:       i915/skl_dmc_ver1_26.bin
firmware:       i915/kbl_dmc_ver1_01.bin
firmware:       i915/skl_guc_ver6_1.bin
```

This is the result on my machine:

![terrain-artifact](https://user-images.githubusercontent.com/1370938/30103813-127078ee-92f4-11e7-9e4d-5764f1ed4129.gif)

**Comment by horde3d** [comment]
I can confirm that I see that error on my Intel Haswell with Mesa 17.0.7 using the OpenGL2 backend as well. But I probably don't have time to investigate further.

**Comment by horde3d** [comment]
I just tried it with an Nvidia NVS4200 and it showed the same artefacts. So it does not seem to be a driver bug.

**Comment by algts** [comment]
I can confirm that it produces artefacts on Linux with radeon 7950 and mesa 12.0.6 and on Linux with Nvidia 1060 with proprietary drivers. No problems on windows (additionally tested on win 7 and radeon 480). So this problem is limited to linux systems.

**Comment by horde3d** [comment]
I can't confirm that, the NVS4200 runs under Windows and it shows the artifacts. 
![bug2](https://user-images.githubusercontent.com/5401047/30292476-9b4c9ec2-9736-11e7-9374-9e731642edff.jpg)
![bug1](https://user-images.githubusercontent.com/5401047/30292475-9b4979fe-9736-11e7-9642-9c6fe88b72ca.jpg)

**Comment by algts** [comment]
Seems to depend on compiler. Probably everything comes to indices generation in terrain extension to this line: *indexItr++ = *(indexItr - 1); 
Visual studio handles this correctly, gcc does not. Since c++11 this is undefined behaviour, so I've changed it to two lines: 
*indexItr = *( indexItr - 1 );
indexItr++;
Will check it tomorrow on linux machine.

**Comment by horde3d** [comment]
You're the man... that's it. Tested it under MinGW with Intel and Nvidia (Windows)
